services:
  huggingface-cache-server:
    image: chocolatefrappe/huggingface-cacheserver:dev
    ports:
      - 36080:36080
    volumes:
      - type: volume
        source: huggingface-cache
        target: /var/cache/huggingface
    stop_grace_period: 5m
    restart: always
volumes:
  huggingface-cache:
