# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json
services:
  huggingface-cache-server:
    image: chocolatefrappe/huggingface-cacheserver:dev
    ports:
      - mode: host
        target: 36080
        published: 36080
        protocol: tcp
    volumes:
      - type: volume
        source: cache
        target: /var/cache/huggingface
    stop_grace_period: 5m
volumes:
  cache:
