# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json
services:
  cacheserver:
    image: chocolatefrappe/huggingface-cacheserver:dev
    ports:
      - 36080:36080
    volumes:
      - type: volume
        source: cache
        target: /var/cache/huggingface
    stop_grace_period: 5m
volumes:
  cache:
